/**
 * Model representing USD/CAD response from public currency api.
 */
export interface UsdCadCurrencyResponse {
    success: boolean
    timestamp: number
    source: string
    quotes: {
        USDAED: number
        USDAFN: number
        USDALL: number
        USDAMD: number
        USDANG: number
        USDAOA: number
        USDARS: number
        USDAUD: number
        USDAWG: number
        USDAZN: number
        USDBAM: number
        USDBBD: number
        USDBDT: number
        USDBGN: number
        USDBHD: number
        USDBIF: number
        USDBMD: number
        USDBND: number
        USDBOB: number
        USDBRL: number
        USDBSD: number
        USDBTC: number
        USDBTN: number
        USDBWP: number
        USDBYN: number
        USDBYR: number
        USDBZD: number
        USDCAD: number
        USDCDF: number
        USDCHF: number
        USDCLF: number
        USDCLP: number
        USDCNY: number
        USDCOP: number
        USDCRC: number
        USDCUC: number
        USDCUP: number
        USDCVE: number
        USDCZK: number
        USDDJF: number
        USDDKK: number
        USDDOP: number
        USDDZD: number
        USDEGP: number
        USDERN: number
        USDETB: number
        USDEUR: number
        USDFJD: number
        USDFKP: number
        USDGBP: number
        USDGEL: number
        USDGGP: number
        USDGHS: number
        USDGIP: number
        USDGMD: number
        USDGNF: number
        USDGTQ: number
        USDGYD: number
        USDHKD: number
        USDHNL: number
        USDHRK: number
        USDHTG: number
        USDHUF: number
        USDIDR: number
        USDILS: number
        USDIMP: number
        USDINR: number
        USDIQD: number
        USDIRR: number
        USDISK: number
        USDJEP: number
        USDJMD: number
        USDJOD: number
        USDJPY: number
        USDKES: number
        USDKGS: number
        USDKHR: number
        USDKMF: number
        USDKPW: number
        USDKRW: number
        USDKWD: number
        USDKYD: number
        USDKZT: number
        USDLAK: number
        USDLBP: number
        USDLKR: number
        USDLRD: number
        USDLSL: number
        USDLTL: number
        USDLVL: number
        USDLYD: number
        USDMAD: number
        USDMDL: number
        USDMGA: number
        USDMKD: number
        USDMMK: number
        USDMNT: number
        USDMOP: number
        USDMRO: number
        USDMUR: number
        USDMVR: number
        USDMWK: number
        USDMXN: number
        USDMYR: number
        USDMZN: number
        USDNAD: number
        USDNGN: number
        USDNIO: number
        USDNOK: number
        USDNPR: number
        USDNZD: number
        USDOMR: number
        USDPAB: number
        USDPEN: number
        USDPGK: number
        USDPHP: number
        USDPKR: number
        USDPLN: number
        USDPYG: number
        USDQAR: number
        USDRON: number
        USDRSD: number
        USDRUB: number
        USDRWF: number
        USDSAR: number
        USDSBD: number
        USDSCR: number
        USDSDG: number
        USDSEK: number
        USDSGD: number
        USDSHP: number
        USDSLE: number
        USDSLL: number
        USDSOS: number
        USDSRD: number
        USDSTD: number
        USDSVC: number
        USDSYP: number
        USDSZL: number
        USDTHB: number
        USDTJS: number
        USDTMT: number
        USDTND: number
        USDTOP: number
        USDTRY: number
        USDTTD: number
        USDTWD: number
        USDTZS: number
        USDUAH: number
        USDUGX: number
        USDUYU: number
        USDUZS: number
        USDVEF: number
        USDVES: number
        USDVND: number
        USDVUV: number
        USDWST: number
        USDXAF: number
        USDXAG: number
        USDXAU: number
        USDXCD: number
        USDXDR: number
        USDXOF: number
        USDXPF: number
        USDYER: number
        USDZAR: number
        USDZMK: number
        USDZMW: number
        USDZWL: number
    }
}
